# Generated by Django 3.2.12 on 2023-12-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='identificationNumber',
            field=models.CharField(default='', max_length=50),
        ),
    ]
