# Generated by Django 3.2.12 on 2023-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20231213_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='casedetails',
            fields=[
                ('caseno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('offense', models.CharField(max_length=50)),
                ('submitingofficername', models.CharField(blank=True, default='user', max_length=50)),
                ('submitingofficerid', models.CharField(max_length=50)),
                ('victim', models.CharField(max_length=50)),
                ('suspect', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(max_length=50)),
                ('seizure', models.CharField(max_length=50)),
            ],
        ),
    ]
