# Generated by Django 3.2.12 on 2023-12-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_casedetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casedetails',
            table='casedetail',
        ),
    ]
