# Generated by Django 3.2.12 on 2023-12-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_casedetails_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterModelTable(
            name='casedetails',
            table='usercasedetail',
        ),
    ]
