# Generated by Django 5.0.2 on 2024-02-18 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20231218_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='casedetails',
        ),
        migrations.DeleteModel(
            name='userdetails',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='identificationNumber',
        ),
    ]
