# Generated by Django 5.0.2 on 2024-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.CharField(choices=[('O', 'Online'), ('F', 'Offline')], max_length=1)),
            ],
            options={
                'db_table': 'onof',
            },
        ),
    ]
